stages:
  - build
  #  - lint_format
  - migrations
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - docker network create botNetwork || true
    - cp ${ENBOT_ENV} ./app/.env
    - cp ${ENBOT_TEST_ENV} ./app/.env-test
    - cp ${AI_ENV} ./ai/.env
    - cp ${NATS_MG_ENV} ./nats-mg/.env
  script:
    - docker build -t enbot-image .
    - docker build -t ai-image ./ai/
    - docker build -t nats-mg-image ./nats-mg/

#Lint:
#  stage: lint_format
#  script:
#    - docker run --rm --network botNetwork enbot-image ruff check
#
#Format:
#  stage: lint_format
#  script:
#    - docker run --rm --network botNetwork enbot-image ruff format --check

Migrations:
  stage: migrations
  script:
    - docker run --rm --network botNetwork enbot-image alembic upgrade head -v

Tests:
  stage: test
  script:
    - docker run --rm --network botNetwork enbot-image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
