"""add words

Revision ID: 95763ddadaa1
Revises: 9e2acba604b2
Create Date: 2026-03-04 18:32:31.837548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "95763ddadaa1"
down_revision: Union[str, None] = "9e2acba604b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("en", sa.String(length=50), nullable=False),
        sa.Column("ru", sa.String(length=50), nullable=True),
        sa.Column("trans", sa.String(length=50), nullable=True),
        sa.Column("ru_full", sa.Text(), nullable=True),
        sa.Column("trans_full", sa.Text(), nullable=True),
        sa.Column("audio_id", sa.Text(), nullable=True),
        sa.Column("image_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("id", name=op.f("uq_words_id")),
    )
    op.create_table(
        "words_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("stage", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_words_users_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name=op.f("fk_words_users_word_id_words"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words_users")),
    )
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.drop_table("words_users")
    op.drop_table("words")
    # ### end Alembic commands ###
